MauroMoreno\DataFactory\Entity\IncidencePlayer:
  access_type: public_method
  exclusion_policy: ALL
  properties:
    id:
      type: "int"
      xml_attribute: true
    name:
      type: "string"
      xml_value: true
