MauroMoreno\DataFactory\Entity\MatchSheet:
  access_type: public_method
  exclusion_policy: ALL
  properties:
    id:
      type: "int"
      xml_attribute: true
    date:
      type: "int"
      xml_attribute: true
      serialized_name: "dia"
    day:
      type: "string"
      xml_attribute: true
      serialized_name: "nombreDia"
    hour:
      type: "string"
      xml_attribute: true
      serialized_name: "horario"
    hour_status:
      type: "string"
      accessor:
        getter: "getHourStatus"
        setter: "setHourStatus"
      serialized_name: "horaEstadoEvento"
    incidences:
      type: "array<MauroMoreno\\DataFactory\\Entity\\Incidence>"
      xml_list:
        entry_name: incidencia
      serialized_name: incidencias
    instance:
      type: "string"
      xml_attribute: true
      serialized_name: "fecha"
    level:
      type: "string"
      xml_attribute: true
      serialized_name: "nombrenivel"
    status:
      type: "MauroMoreno\\DataFactory\\Entity\\Status"
      serialized_name: "estadoEvento"
    teams:
      type: "array<MauroMoreno\\DataFactory\\Entity\\Team>"
      xml_list:
        entry_name: equipo
        inline: true
    timezone:
      type: "int"
      xml_attribute: true
      serialized_name: "gmt"
    type:
      type: "string"
      xml_attribute: true
      serialized_name: "tipo"
